import { NextResponse } from "next/server";
import { kv } from "@vercel/kv";

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);

  const code = searchParams.get("code");
  const state = searchParams.get("state");

  if (!code || !state) {
    return NextResponse.redirect(
      `${process.env.NEXT_PUBLIC_BASE_URL}/spotify/success?status=error`,
    );
  }

  const stored = await kv.get<{
    playlistName: string;
    trackUris: string[];
  }>(`oauth:${state}`);

  if (!stored) {
    console.error("Missing stored OAuth payload");
    return NextResponse.redirect(
      `${process.env.NEXT_PUBLIC_BASE_URL}/spotify/success?status=error`,
    );
  }

  await kv.del(`oauth:${state}`);

  const { playlistName, trackUris } = stored;

  try {
    // Exchange code
    const tokenRes = await fetch("https://accounts.spotify.com/api/token", {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        Authorization:
          "Basic " +
          Buffer.from(
            `${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`,
          ).toString("base64"),
      },
      body: new URLSearchParams({
        grant_type: "authorization_code",
        code,
        redirect_uri: process.env.SPOTIFY_REDIRECT_URI!,
      }),
    });

    const tokenData = await tokenRes.json();
    const accessToken = tokenData.access_token;

    if (!accessToken) throw new Error("Token exchange failed");

    // Create playlist
    const playlistRes = await fetch("https://api.spotify.com/v1/me/playlists", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: playlistName || `FairPlay - ${new Date().toLocaleDateString()}`,
        description: "Generated by FairPlay",
        public: false,
      }),
    });

    const playlistData = await playlistRes.json();

    if (!playlistRes.ok || !playlistData.id) {
      throw new Error("Failed to create playlist");
    }

    const playlistId = playlistData.id;

    const validUris = trackUris.filter(
      (uri) => typeof uri === "string" && uri.startsWith("spotify:track:"),
    );

    for (let i = 0; i < validUris.length; i += 100) {
      await fetch(`https://api.spotify.com/v1/playlists/${playlistId}/items`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          uris: validUris.slice(i, i + 100),
        }),
      });
    }

    return NextResponse.redirect(
      `${process.env.NEXT_PUBLIC_BASE_URL}/spotify/success?status=success`,
    );
  } catch (err) {
    console.error("Spotify error:", err);
    return NextResponse.redirect(
      `${process.env.NEXT_PUBLIC_BASE_URL}/spotify/success?status=error`,
    );
  }
}
